/**
 * UCMidtier
 * java -jar ../swagger-codegen-cli.jar generate -i http://localhost:8082/swagger/docs/v1 -l typescript-fetch -o C:\proj\uc_shared\src
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as querystring from "querystring";
import * as url from "url";

require("portable-fetch");
//import * as assign from "core-js/library/fn/object/assign";
const assign = require('object-assign');
const isomorphicFetch = fetch;

interface Dictionary<T> { [index: string]: T; }
export interface FetchAPI { (url: string, init?: any): Promise<any>; }

export const BASE_PATH = (!process.env.BROWSER) ? ((process.env && process.env.BASE_PATH) || 'https://www.undergroundcellar.com') : '';
